# Generated by Django 3.1.2 on 2020-11-03 03:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0004_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Reviewrating',
        ),
    ]
